### ISSUE TITLE
Experiment with sample code (not working)

### ISSUE THREAD

**Issue by GOVYANSONG** [matrix-org/rust-opa-wasm#19]
I have a OPA REGO policy that has been tested and evaluated without any issue with opa test/evaluate. I run opa build to generate policy.wasm. I adopted the code sample from readme page and it compiled and run without any issue EXCEPT the evaluation result is always empty e.g. []. 

cargo version:

cargo 1.61.0 (a028ae4 2022-04-29)

cargo toml:

[package]
name = "oparust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true

[dependencies]
anyhow = "1.0.58"
tokio = { version = "1.19.2", features = ["full"] }
wasmtime = { version = "0.38.1", default-features = false, features = ["async", "cranelift"] }
opa-wasm = { git = "https://github.com/matrix-org/rust-opa-wasm" }
serde_json = "1.0.82"

OPA version

Version: 0.42.1
Build Commit: 60b7193
Build Timestamp: 2022-07-08T06:10:27Z
Build Hostname: 4f65c678ea38
Go Version: go1.18.3
Platform: linux/amd64
WebAssembly: available

Any suggestion? thanks in advance.

**Comment by jondot** [comment]
Can you include the policy and input data you've used? (please remember to remove sensitive information from those if it exists)

**Comment by GOVYANSONG** [comment]
policy file:

package policies.api.policy1

gql_restricted = [
    {"kind": "mutation", "op": "T_updateCatalog", "granted": { x | x := ["1151", "1153"][_] }},
    {"kind": "mutation", "op": "T_approveBatchPR", "granted": { x | x := ["1151", "1153"][_] }},
    {"kind": "mutation", "op": "T_submitBatchPR", "granted": { x | x := ["1150", "1153"][_] }}
]

authz { 
    allow   
    not deny
}

allow { true }

deny { 
	roles := { x | x := input.roles[_] }
	gql_restricted[k].kind == input.kind
    gql_restricted[k].op == input.op
    count(roles & gql_restricted[k].granted) == 0
}


data: N/A

input:

{"kind": "mutation", "op": "T_submitBatchPR", "roles": ["1150", "XYZ"] }

**Comment by GOVYANSONG** [comment]
rego test cases:

package main_test

import data.main

test_unrestricted_granted {
    main.decision == {
        "allow" : true
    } with input as {"kind": "non-gql-kind", "op": "op-anything"}
}

test_restricted_granted {
    main.decision == {
        "allow" : true
    } with input as {"kind": "mutation", "op": "T_submitBatchPR", "roles": ["1150", "XYZ"] }
}

test_restricted_rejected {
    main.decision == {
        "allow" : false
    } with input as {"kind": "mutation", "op": "T_submitBatchPR", "roles": ["XYZ"] }
}

# build policy wasm
opa build -t wasm -e main.decision  main.rego ./policies/api/policy1.rego --output target/bundle.tar.gz

# evaluate with stdin: {"kind": "mutation", "op": "T_submitBatchPR", "roles": ["1150", "0"]}, press CTRL+D to finish input
opa eval -b target/bundle.tar.gz data.main.decision --stdin-input

**Comment by GOVYANSONG** [comment]
main.rego

package main

applicable_policy = {
    "graphql" : "api"
}

name = applicable_policy["graphql"]
policy = "policy1"

router[policy] = data.policies[name][policy].authz

decision["allow"] = router[policy]

**Comment by GOVYANSONG** [comment]
FYI I tried the CLI tool and still no luck :(

RUST_LOG=info cargo run --features=cli --      \
    --module ./policy.wasm       \
	--data-path ./data.json      \
    --input '{"kind": "mutation", "op": "T_submitBatchPR", "roles": ["1150", "XYZ"] }' \
    --entrypoint 'main.decision'

**Comment by GOVYANSONG** [comment]
FYI after thoroughly compared your rego and mine, I noticed that your entrypoint is set at package level e.g. 'test' but mine is configured at rule/variable level e.g. main.decision. Once i updated entrypoint to 'main', both opa and your sdk worked nicely.
